### ISSUE TITLE
Input field is missing at update password 

### ISSUE THREAD

**Issue by memeteli** [adapt-security/adapt-authoring-ui#181]
So we can not enter a new password, it logs out error on browsr:
```adapt.js:1 SweetAlert2: Unknown icon! Expected "success", "error", "warning", "info" or "question", got "input"```

After we click save without entering a password we will get error on console:

```
2022-04-19T12:17:29.679Z error server TypeError: Cannot read properties of undefined (reading 'errors')
    at Function.validateReset (file:///C:/Users/amaimaiti/Desktop/adapt/adapt-autoring-tool/node_modules/adapt-authoring-localauth/lib/PasswordUtils.js:115:22)
    at LocalAuthModule.changePasswordHandler (file:///C:/Users/amaimaiti/Desktop/adapt/adapt-autoring-tool/node_modules/adapt-authoring-localauth/lib/LocalAuthModule.js:238:29)
```

![image](https://user-images.githubusercontent.com/54360982/164002182-1b8468cd-7da2-43cb-aef0-a8e2dd9735b4.png)

**Comment by fkcailiniyazi** [comment]
And the password was updated. I can't access my dashboard anymore... 😄

**Comment by taylortom** [comment]
Fixed

**Comment by canstudios-scottd** [comment]
Change password is not available only [reset password] which sends an email

**Comment by taylortom** [comment]
Apologies, I forgot that this feature's disabled when email resets are set up. I've now turned off the email resets, so this should be testable again 😄

**Comment by joe-allen-89** [comment]
It's appearing for me and working as expected when changing password.
