### ISSUE TITLE
Content plugin upload broken

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-ui#41]
```
2020-11-25T11:45:06.118Z error server MongoDBError: Failed to insert new document, doc parameter must be an object
    at MongoDBModule.insert (/home/tom/Projects/adapt/adapt-authoring/node_modules/adapt-authoring-mongodb/lib/MongoDBModule.js:74:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by taylortom** [comment]
Fixed
